### ISSUE TITLE
Update the wrapper scripts to mount individual paths

### ISSUE THREAD

**Issue by verbotenj** [blinklabs-io/cardano-up#188]
Fix up the wrapper script to mount individual paths rather than / to account for it

```
Fetching package registry https://github.com/blinklabs-io/cardano-up/archive/refs/heads/main.zip
Installing package cardano-node (= 8.9.1)
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: mkdir /host/Users: file exists: unknown.
ERROR: run hook script exited with error: exit status 125
```

**Comment by wolf31o2** [comment]
This is caused by the default Docker Desktop configuration which doesn't map `/` as an allowed path into the container VM. We should support the default provided paths.

**Comment by agaffney** [comment]
The default allowed directories with Docker Desktop for Mac are:

* `/Users`
* `/Volumes`
* `/private`
* `/tmp`
* `/var/folders`
