### ISSUE TITLE
Add a hydra package

### ISSUE THREAD

**Issue by ch1bo** [blinklabs-io/cardano-up#193]
Is there appetite for this?

`hydra-node` is best run as a docker container and a [setup like the demo](https://hydra.family/head-protocol/docs/getting-started/demo/with-docker) could be scaffolded, or an even simpler "one hydra-node sandbox" to get started sounds fitting?

**Comment by Quantumplation** [comment]
Sounds like offline mode could be helpful for the "one hydra-node sandbox" option 😏

**Comment by wolf31o2** [comment]
Do we need tui/tools to have something useful, or is the node a sufficient starting point?

**Comment by wolf31o2** [comment]
This has been moved to blinklabs-io/cardano-up-packages#4

**Comment by wolf31o2** [comment]
FYI, I started this by introducing `devnet` into gOuroboros and our cardano-node Docker images to make it easier to hook up to cardano-up or start up a devnet node with our images, in general.
