### ISSUE TITLE
Add a cardano-wallet package

### ISSUE THREAD

**Issue by wolf31o2** [blinklabs-io/cardano-up#212]

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by wolf31o2** [comment]
Moved to blinklabs-io/cardano-up-packages#6
