### ISSUE TITLE
Clean up data dir(s) on uninstall

### ISSUE THREAD

**Issue by agaffney** [blinklabs-io/cardano-up#60]
When a package is uninstalled, it's data dir(s) should also be removed. This includes the package-specific data dir and the context shared data dir (if this is the last package). We can make this behavior optional with a commandline flag.

**Comment by wolf31o2** [comment]
Note: existing "uninstall" removals are done on the host, while any data created by a container running as root may be owned by root, so we may need to use something like a busybox container for cleaning up

**Comment by agaffney** [comment]
> Note: existing "uninstall" removals are done on the host, while any data created by a container running as root may be owned by root, so we may need to use something like a busybox container for cleaning up

I split this part to a separate ticket to do as an enhancement
